
name: digital_krishi_officer
description: AI-based farmer query support system for Kerala

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.0
  google_fonts: ^4.0.0

  # Audio Recording & Playback
  record: ^5.0.0
  just_audio: ^0.9.0
  path_provider: ^2.0.0
  permission_handler: ^10.0.0

  # Camera & Image Capture
  camera: ^0.10.0
  image_picker: ^0.8.0
  image: ^4.0.0

  # Networking & API
  http: ^0.13.0
  dio: ^5.0.0
  json_annotation: ^4.8.0

  # State Management
  provider: ^6.0.0
  flutter_bloc: ^8.0.0

  # Local Storage
  shared_preferences: ^2.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0

  # Utilities
  intl: ^0.18.0
  uuid: ^3.0.0
  geolocator: ^9.0.0
  connectivity_plus: ^3.0.0

  # Firebase (for authentication)
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0

  # Text-to-Speech
  flutter_tts: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.0
  build_runner: ^2.3.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/

  fonts:
    - family: Manjari
      fonts:
        - asset: assets/fonts/Manjari-Regular.ttf
        - asset: assets/fonts/Manjari-Bold.ttf
          weight: 700
