
# Default values for digital-krishi-officer

# Global configuration
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: "fast-ssd"

# Application configuration
app:
  name: digital-krishi-officer
  version: "1.0.0"
  environment: production

# Backend configuration
backend:
  replicaCount: 3
  image:
    repository: digitalkrishi/backend
    tag: "latest"
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
      nvidia.com/gpu: 1
    limits:
      cpu: 2
      memory: 4Gi
      nvidia.com/gpu: 1

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  service:
    type: ClusterIP
    port: 80
    targetPort: 8000

# Frontend configuration
frontend:
  replicaCount: 2
  image:
    repository: digitalkrishi/frontend
    tag: "latest"
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  service:
    type: ClusterIP
    port: 80

# Database configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: "secure_password_here"
    username: "krishi_user"
    password: "secure_password_here"
    database: "krishi_db"

  primary:
    persistence:
      enabled: true
      size: 50Gi
      storageClass: "fast-ssd"

    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi

# Redis configuration
redis:
  enabled: true
  auth:
    enabled: false

  master:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "fast-ssd"

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi

# Milvus configuration
milvus:
  enabled: true
  cluster:
    enabled: false

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 4Gi

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

  hosts:
    - host: api.digitalkrishi.com
      paths:
        - path: /
          pathType: Prefix
          service: backend
    - host: dashboard.digitalkrishi.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend

  tls:
    - secretName: krishi-tls
      hosts:
        - api.digitalkrishi.com
        - dashboard.digitalkrishi.com

# Monitoring configuration
monitoring:
  prometheus:
    enabled: true

  grafana:
    enabled: true
    adminPassword: "admin123"

# Security configuration
security:
  networkPolicies:
    enabled: true

  podSecurityPolicy:
    enabled: true

# Persistence configuration
persistence:
  models:
    enabled: true
    size: 100Gi
    storageClass: "fast-ssd"
    accessMode: ReadWriteOnce

  uploads:
    enabled: true
    size: 50Gi
    storageClass: "standard"
    accessMode: ReadWriteMany

# Node affinity for GPU nodes
nodeAffinity:
  gpu:
    enabled: true
    nodeSelector:
      accelerator: nvidia-tesla-k80
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
